import "@/styles/index.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Vibestart",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="dark">
			<body>{children}</body>
		</html>
	);
}
